# Create a book
POST localhost:8080/api/books
Content-Type: application/json

{
  "title": "1984",
  "publicationYear": 1984,
  "isbn": "9789876543210",
  "authors": [
    {
      "name": "George Orwell"
    }
  ]
}

###

# Create a copy
POST localhost:8080/api/copies
Content-Type: application/json

{
  "book": {
    "isbn": "9789876543210"
  },
  "status": "AVAILABLE"
}

###

# Create a second copy
POST localhost:8080/api/copies
Content-Type: application/json

{
  "book": {
    "isbn": "9789876543210"
  },
  "status": "AVAILABLE"
}

###

# Create a customer
POST localhost:8080/api/customers
Content-Type: application/json

{
  "firstName": "Joe",
  "lastName": "Mama",
  "email": "joe.mama@example.com"
}

###

# Borrow a copy
POST localhost:8080/api/customers/1/borrow/9789876543210

###

# Reserve a copy
POST localhost:8080/api/customers/1/reserve/9789876543210

###

# Checkout the reserved copy
PUT localhost:8080/api/copies/2/checkout