POST http://localhost:8080/api/books
Content-Type: application/json

{
  "title": "Test book",
  "authors": [
    {
      "name": "Joe Mama"
    },
    {
      "name": "Jane Mama"
    }
  ],
  "publicationYear": 2077,
  "isbn": "1234567890"
}