global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'library-management'
    static_configs:
      - targets: [ 'library-management-app:8080' ]
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s