PUT http://localhost:8080/api/books/9781234567890
Content-Type: application/json

{
  "title": "Test Book 2",
  "publicationYear": 1984,
  "isbn": "9791234567890",
  "authors": [
    {
      "name": "Joe Mama"
    }
  ]
}