# Delete copy
DELETE http://localhost:8080/api/copies/1

###

# Delete another copy
DELETE http://localhost:8080/api/copies/2

###

# Try to delete non-existent copy
DELETE http://localhost:8080/api/copies/999
