# Borrow copy
PUT http://localhost:8080/api/copies/1/borrow

###

# Return copy
PUT http://localhost:8080/api/copies/1/return

###

# Reserve copy
PUT http://localhost:8080/api/copies/1/reserve

###

# Unreserve copy
PUT http://localhost:8080/api/copies/1/unreserve

###

# Mark copy as lost
PUT http://localhost:8080/api/copies/1/lost

###

# Try to borrow non-existent copy
PUT http://localhost:8080/api/copies/999/borrow

###

# Try to return copy that isn't borrowed
PUT http://localhost:8080/api/copies/2/return