{
 "title": "Library Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Response Time",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{uri=~\"/api/.*\"}[1m])) by (uri) / sum(rate(http_server_requests_seconds_count{uri=~\"/api/.*\"}[1m])) by (uri)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Resources Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "system_cpu_usage", "legendFormat": "CPU" },
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\"}) / sum(jvm_memory_max_bytes{area=\"heap\"})",
     "legendFormat": "Heap Memory"
    }
   ]
  },
  {
   "title": "DB Connection Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "hikaricp_connections_active / hikaricp_connections_max",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=~\"/api/(books|reservations).*\"}[5m]))",
     "legendFormat": "Customers"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=~\"/api/(admin|desk).*\"}[5m]))",
     "legendFormat": "Staff"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=~\"/api/.*\",status=~\"5..\"}[1m])) / sum(rate(http_server_requests_seconds_count{uri=~\"/api/.*\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}