### Add Book 11
POST http://localhost:8080/api/books
Content-Type: application/json

{
  "title": "Test Book 11",
  "publicationYear": 2023,
  "isbn": "9781111111111",
  "authors": [
    {
      "name": "Joe Mama"
    }
  ]
}

### Add Book 12
POST http://localhost:8080/api/books
Content-Type: application/json

{
  "title": "Test Book 12",
  "publicationYear": 2022,
  "isbn": "9781111111112",
  "authors": [
    {
      "name": "Jane Mama"
    },
    {
      "name": "The Goober"
    }
  ]
}

### Add Book 13
POST http://localhost:8080/api/books
Content-Type: application/json

{
  "title": "Test Book 13",
  "publicationYear": 2024,
  "isbn": "9781111111113",
  "authors": [
    {
      "name": "Joe Mama Jr."
    }
  ]
}

### Add Book 14
POST http://localhost:8080/api/books
Content-Type: application/json

{
  "title": "Test Book 14",
  "publicationYear": 2023,
  "isbn": "9781111111114",
  "authors": [
    {
      "name": "Charlie Charles"
    }
  ]
}

### Add Book 15
POST http://localhost:8080/api/books
Content-Type: application/json

{
  "title": "Test Book 15",
  "publicationYear": 2021,
  "isbn": "9781111111115",
  "authors": [
    {
      "name": "Charlie Charles Jr."
    },
    {
      "name": "Alice Allison"
    }
  ]
}

### Add Book 16
POST http://localhost:8080/api/books
Content-Type: application/json

{
  "title": "Test Book 16",
  "publicationYear": 2025,
  "isbn": "9781111111116",
  "authors": [
    {
      "name": "Bob Builder"
    }
  ]
}

### Add Book 17
POST http://localhost:8080/api/books
Content-Type: application/json

{
  "title": "Test Book 17",
  "publicationYear": 2022,
  "isbn": "9781111111117",
  "authors": [
    {
      "name": "Carol Carter"
    },
    {
      "name": "David Davis"
    }
  ]
}

### Add Book 18
POST http://localhost:8080/api/books
Content-Type: application/json

{
  "title": "Test Book 18",
  "publicationYear": 2024,
  "isbn": "9781111111118",
  "authors": [
    {
      "name": "The Goober"
    }
  ]
}

### Add Book 19
POST http://localhost:8080/api/books
Content-Type: application/json

{
  "title": "Test Book 19",
  "publicationYear": 2023,
  "isbn": "9781111111119",
  "authors": [
    {
      "name": "Joe Mama"
    },
    {
      "name": "Jane Mama"
    }
  ]
}

### Add Book 20
POST http://localhost:8080/api/books
Content-Type: application/json

{
  "title": "Test Book 20",
  "publicationYear": 2025,
  "isbn": "9781111111120",
  "authors": [
    {
      "name": "Alice Allison"
    }
  ]
}

### Add Book 21
POST http://localhost:8080/api/books
Content-Type: application/json

{
  "title": "Test Book 21",
  "publicationYear": 2024,
  "isbn": "9781111111121",
  "authors": [
    {
      "name": "Bob Builder"
    }
  ]
}

### Add Book 22
POST http://localhost:8080/api/books
Content-Type: application/json

{
  "title": "Test Book 22",
  "publicationYear": 2022,
  "isbn": "9781111111122",
  "authors": [
    {
      "name": "Carol Carter"
    },
    {
      "name": "Charlie Charles"
    }
  ]
}

### Add Book 23
POST http://localhost:8080/api/books
Content-Type: application/json

{
  "title": "Test Book 23",
  "publicationYear": 2023,
  "isbn": "9781111111123",
  "authors": [
    {
      "name": "David Davis"
    }
  ]
}

### Add Book 24
POST http://localhost:8080/api/books
Content-Type: application/json

{
  "title": "Test Book 24",
  "publicationYear": 2025,
  "isbn": "9781111111124",
  "authors": [
    {
      "name": "Joe Mama Jr."
    },
    {
      "name": "The Goober"
    }
  ]
}

### Add Book 25
POST http://localhost:8080/api/books
Content-Type: application/json

{
  "title": "Test Book 25",
  "publicationYear": 2024,
  "isbn": "9781111111125",
  "authors": [
    {
      "name": "Charlie Charles Jr."
    }
  ]
}

### Add Book 26
POST http://localhost:8080/api/books
Content-Type: application/json

{
  "title": "Test Book 26",
  "publicationYear": 2022,
  "isbn": "9781111111126",
  "authors": [
    {
      "name": "Alice Allison"
    },
    {
      "name": "Bob Builder"
    }
  ]
}

### Add Book 27
POST http://localhost:8080/api/books
Content-Type: application/json

{
  "title": "Test Book 27",
  "publicationYear": 2023,
  "isbn": "9781111111127",
  "authors": [
    {
      "name": "Jane Mama"
    }
  ]
}

### Add Book 28
POST http://localhost:8080/api/books
Content-Type: application/json

{
  "title": "Test Book 28",
  "publicationYear": 2025,
  "isbn": "9781111111128",
  "authors": [
    {
      "name": "Carol Carter"
    },
    {
      "name": "David Davis"
    }
  ]
}

### Add Book 29
POST http://localhost:8080/api/books
Content-Type: application/json

{
  "title": "Test Book 29",
  "publicationYear": 2024,
  "isbn": "9781111111129",
  "authors": [
    {
      "name": "Joe Mama"
    },
    {
      "name": "The Goober"
    }
  ]
}

### Add Book 30
POST http://localhost:8080/api/books
Content-Type: application/json

{
  "title": "Test Book 30",
  "publicationYear": 2023,
  "isbn": "9781111111130",
  "authors": [
    {
      "name": "Charlie Charles"
    }
  ]
}