# Get all books
GET http://localhost:8080/api/books

###

# Get specific book by ISBN
GET http://localhost:8080/api/books/9781234567890

###

# Search by title
GET http://localhost:8080/api/books/search?title=Gatsby

###

# Search by author
GET http://localhost:8080/api/books/search?authorName=Orwell

###

# Search with pagination
GET http://localhost:8080/api/books/search?authorName=Joe&size=2&page=0

###

# Get non-existent book
GET http://localhost:8080/api/books/9999999999999