# Create a user librarian
POST localhost:8080/api/register
Content-Type: application/json

{
  "username": "librarian1",
  "password": "secret123",
  "role": "LIBRARIAN"
}

###

# Login as librarian
POST localhost:8080/api/login
Content-Type: application/json

{
  "username": "librarian1",
  "password": "secret123"
}